# API list not to do app


### FETCH ALL TASKS AND A SINGLE TASK BY ID (OPTIONAL)
GET http://localhost:8000/api/v1/FFFF

### CREATE NEW LIST AND INSERT
POST http://localhost:8000/api/v1
Content-Type:  application/json

{
    "task": "Eating",
    "hr": "20"
}

### UPDATE TASK
PATCH http://localhost:8000/api/v1
Content-Type:  application/json

{
    "_id": "hendra.here@yahoo.com",
    "todo": true
}


### DELETE TASK
DELETE  http://localhost:8000/api/v1
Content-Type:  application/json

{
    "_id": "hendra.here@yahoo.com"
}