# API list not to do app


### FETCH ALL TASKS AND A SINGLE TASK BY ID (OPTIONAL)
GET http://localhost:8000/api/v1/

### CREATE NEW LIST AND INSERT
POST http://localhost:8000/api/v1/
Content-Type:  application/json

{
    "task": "Fishing",
    "hr": "10"
}

### UPDATE TASK
PATCH http://localhost:8000/api/v1
Content-Type:  application/json

{
    "id": "612ddc02f379984ea09f2504",
    "todo": false
}

### DELETE TASK
DELETE  http://localhost:8000/api/v1
Content-Type:  application/json

{
    "ids": [ "612ed3ab6f89efba35af129b"
    ]
}